#!/usr/bin/env ruby

require "dupe/args"
require "dupe/finder"
require "dupe/hashstore"

# parse args
args = Dupe::Args::parse(ARGV)

# get sequence of file paths
path_enum = Dupe::Finder::interesting_files(args.path)
storage = Dupe::HashStore.new

# hash files
path_enum.each_entry do |path|
  digest = Dupe::Finder.file_digest(path)
  storage.push(digest, path)
end

# let hash store sync
storage.sync

#
# iterate over (hash, [path]) pairs
storage.each_pair do |digest,paths|
  if paths.count == 1
    next
  end

  # we have a dupe, so print out the group
end
